USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS ADP_EMPLOYEE_SKILLS
(
    EMPLOYEE_ID   VARCHAR(10),
    SKILL_ID      VARCHAR(6),
    PROFICIENCY   NUMBER(2,0),
    IS_PRIMARY    BOOLEAN,

    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);