USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS ADP_EMPLOYEES
(
    EMPLOYEE_ID        VARCHAR(10),
    ROLE               VARCHAR(40),
    LEVEL              VARCHAR(4),
    BUSINESS_UNIT      VARCHAR(10),
    LOCATION           VARCHAR(10),
    PRIMARY_SKILL_ID   VARCHAR(6),
    COST_RATE_HOURLY   NUMBER(8,2),
    HIRE_DATE          DATE,
    EMPLOYMENT_STATUS  VARCHAR(12),

    CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);