USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RESOURCE_GAPS_HISTORY
(
    PERIOD_MONTH     DATE,
    SKILL_ID         VARCHAR(6),
    BUSINESS_UNIT    VARCHAR(10),
    UNMET_HOURS      NUMBER(11,1),

    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);