USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS SMARTSHEET_PROJECTS
(
    PROJECT_ID             VARCHAR(12),
    PROJECT_NAME           VARCHAR(80),
    BUSINESS_UNIT          VARCHAR(10),
    PRIORITY               NUMBER(2),
    STRATEGIC_VALUE        NUMBER(5,3),
    START_DATE             DATE,
    END_DATE               DATE,
    STATUS                 VARCHAR(20),
    ESTIMATED_MARGIN_PCT   NUMBER(5,3),

    CREATED_AT             TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);