USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS NETSUITE_FINANCIAL_ACTUALS
(
    PROJECT_ID      VARCHAR(12),
    PERIOD_MONTH    DATE,
    BOOKED_HOURS    NUMBER(11,1),
    ACTUAL_HOURS    NUMBER(11,1),
    BOOKED_COST     NUMBER(14,2),
    ACTUAL_COST     NUMBER(14,2),

    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);