USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS SMARTSHEET_ALLOCATIONS
(
    ALLOCATION_ID     VARCHAR(12),
    PROJECT_ID        VARCHAR(12),
    TASK_ID           VARCHAR(10),
    EMPLOYEE_ID       VARCHAR(10),
    SKILL_ID          VARCHAR(6),
    PERIOD_MONTH      DATE,
    ALLOCATED_HOURS   NUMBER(9,1),

    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);