USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS DEMAND_HISTORY
(
    PERIOD_MONTH     DATE,
    SKILL_ID         VARCHAR(6),
    BUSINESS_UNIT    VARCHAR(10),
    DEMAND_HOURS     NUMBER(11,1),
    IS_ACTUAL        BOOLEAN,

    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);