USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS SMARTSHEET_TASKS
(
    TASK_ID             VARCHAR(10),
    PROJECT_ID          VARCHAR(12),
    PHASE               VARCHAR(20),
    REQUIRED_SKILL_ID   VARCHAR(6),
    PLANNED_HOURS       NUMBER(9,1),
    TASK_START          DATE,
    TASK_END            DATE,

    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);