USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS NETSUITE_PIPELINE_OPPORTUNITIES
(
    OPPORTUNITY_ID    VARCHAR(10),
    BUSINESS_UNIT     VARCHAR(10),
    EXPECTED_START    DATE,
    WIN_PROBABILITY   NUMBER(4,2),
    ESTIMATED_VALUE   NUMBER(14,0),
    PRIORITY          NUMBER(2),
    STAGE             VARCHAR(20),

    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);