USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS ADP_AVAILABILITY
(
    EMPLOYEE_ID      VARCHAR(10),
    PERIOD_MONTH     DATE,
    FTE_FRACTION     NUMBER(5,3),
    PTO_HOURS        NUMBER(7,1),
    CAPACITY_HOURS   NUMBER(7,1),

    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);