USE DATABASE IRM_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS NETSUITE_PIPELINE_SKILL_DEMAND
(
    OPPORTUNITY_ID   VARCHAR(10),
    SKILL_ID         VARCHAR(6),
    EXPECTED_HOURS   NUMBER(9),

    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);